version: "3.9"
services:
  api-dbsrv01:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: api-dbsrv01
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: api
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: api
      MYSQL_TCP_PORT: 3306
    volumes:
      - api-dbsrv01-data:/var/lib/mysql
      - ./environment/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./environment/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    image: api-srv
    depends_on:
      - api-dbsrv01
    build:
      context: .
      dockerfile: ./environment/go/dockerfile
      args:
        - target=dev
    environment:
      ENV: dev
      APP_NAME: app
      APP_VERSION: DEV
      LOG_LEVEL: info
      PORT: 8080
      DB_URL: api:P@ssw0rd@tcp(api-dbsrv01)/api?charset=utf8&parseTime=True&loc=Local
      Access-Control-Allow-Origin: "*"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
volumes:
  api-dbsrv01-data:
