// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/products": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "商品を保存する",
                "parameters": [
                    {
                        "description": "登録商品",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/products.PostRequestParm"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/products.postProductResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "products.PostRequestParm": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "商品の説明",
                    "type": "string"
                },
                "name": {
                    "description": "商品名",
                    "type": "string"
                },
                "owner_id": {
                    "description": "出品者ID",
                    "type": "string"
                },
                "price": {
                    "description": "商品金額",
                    "type": "integer"
                },
                "stock": {
                    "description": "商品在庫",
                    "type": "integer"
                }
            }
        },
        "products.ProductResponseModel": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "商品の説明",
                    "type": "string"
                },
                "id": {
                    "description": "商品ID",
                    "type": "string"
                },
                "name": {
                    "description": "商品名",
                    "type": "string"
                },
                "owner_id": {
                    "description": "出品者ID",
                    "type": "string"
                },
                "price": {
                    "description": "商品金額",
                    "type": "integer"
                },
                "stock": {
                    "description": "商品在庫",
                    "type": "integer"
                }
            }
        },
        "products.postProductResponse": {
            "type": "object",
            "properties": {
                "product": {
                    "$ref": "#/definitions/products.ProductResponseModel"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
