name: Backend Test Push

on:
  push:

jobs:
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: tag release skip
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/') }}" = "true" ]; then
            exit 1
          fi
        continue-on-error: true

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: testing
        run: |
          go test ./... -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0
